framework:
    workflows:
      comment:
        type: state_machine
        audit_trail:
          enabled: "%kernel.debug%"
        marking_store:
          type: 'method'
          property: 'state'
        supports:
          - App\Entity\Comment
        initial_marking: submitted
        places:
          - submitted
          - spam
          - notspam
          - rejected
          - published
        transitions:
          fail:
            from: submitted
            to:   spam
          pass:
            from: submitted
            to:   notspam
          reject:
            from: notspam
            to:   rejected
          publish:
            from: notspam
            to:   published